---
name: Class-DBI-FormTools
version: v0.0.4
author:
  - David Jack Olrik <david@olrik.dk>
abstract: Build forms with multiple interconnected objects.
license: perl
requires:
  Test::More: 0
  version: 0
provides:
  Class::DBI::FormTools:
    file: lib/Class/DBI/FormTools.pm
    version: v0.0.4
generated_by: Module::Build version 0.2611
